from enum import Enum


class EventStream(str, Enum):
    SCRIPT = "SCRIPT"
    VIDEO = "VIDEO"
    AUDIO = "AUDIO"
    AVATAR = "AVATAR"
    STOCK = "STOCK"
    NOTIFICATION = "NOTIFICATION"


class EventProcessType(str, Enum):
    SCRIPT_GENERATION = "SCRIPT_GENERATION"
    SCRIPT_GENERATED = "SCRIPT_GENERATED"
    VOICE_GENERATED = "VOICE_GENERATED"
    AUDIO_GENERATED = "AUDIO_GENERATED"
    AVATAR_VIDEO_GENERATED = "AVATAR_VIDEO_GENERATED"
    SCRIPT_GENERATION_FAILED = "SCRIPT_GENERATION_FAILED"
    VIDEO_GENERATION = "VIDEO_GENERATION"
    VIDEO_CREATED = "VIDEO_GENERATED"
    SCRIPT_CREATED = "SCRIPT_CREATED"
    VOICE_GENERATION = "VOICE_GENERATION"
    AUDIO_GENERATION = "AUDIO_GENERATION"
    AVATAR_GENERATION = "AVATAR_GENERATION"
    STOCK_VIDEO_DATA_CREATED = "STOCK_VIDEO_DATA_CREATED"
    VIDEO_TASK_CREATED = "VIDEO_TASK_CREATED"
    ERROR_LOGS = "ERROR_LOGS"
    VIDEO_LOGS = "VIDEO_LOGS"
    VIDEO_CLIP_CREATION = "VIDEO_CLIP_CREATION"
    SUBTITLE_GENERATION = "SUBTITLE_GENERATION"
    TITLE_GENERATION = "TITLE_GENERATION"
    GENERATING_SCRIPT = "GENERATING_SCRIPT"
    STOCK_VIDEO_CREATION = "STOCK_VIDEO_CREATION"
    VIDEO_UPLOAD_STARTED = "VIDEO_UPLOAD_STARTED"
    UPLOAD_VIDEO_IN_PROGRESS = "UPLOAD_VIDEO_IN_PROGRESS"
    VIDEO_UPLOADED = "VIDEO_UPLOADED"
    UPLOAD_VIDEO_FAILED = "UPLOAD_VIDEO_FAILED"
    UPLOADING_VIDEO_THUMBNAILS_STARTED = "UPLOADING_VIDEO_THUMBNAILS_STARTED"
    UPLOADING_VIDEO_THUMBNAILS_END = "UPLOADING_VIDEO_THUMBNAILS_END"
    THUMBNAILS_FAILED = "THUMBNAILS_FAILED"


class VideoLogsType(str, Enum):
    VIDEO_GENERATION = "video_generation"
